### ISSUE TITLE
大家有用action编译吗？编译报错

### ISSUE THREAD

**Issue by sanan2015** [chongshengB/rt-n56u#117]
两次更新我尝试编译都没有成功过，之前fork的版本是编译成功上传固件的时候失败，最后没有解决；
昨天fork的版本尝试编译时， Initialization environment报错：

```
.github:1

Process completed with exit code 100.
```

```
Err:19 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 lib32asan4 amd64 7.4.0-1ubuntu1~18.04.1
  404  Not Found [IP: 52.168.50.79 80]
Get:31 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 gperf amd64 3.1-1 [103 kB]
Err:20 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 libx32asan4 amd64 7.4.0-1ubuntu1~18.04.1
  404  Not Found [IP: 52.168.50.79 80]
Err:21 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 lib32ubsan0 amd64 7.4.0-1ubuntu1~18.04.1
  404  Not Found [IP: 52.168.50.79 80]
Err:22 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 libx32ubsan0 amd64 7.4.0-1ubuntu1~18.04.1
  404  Not Found [IP: 52.168.50.79 80]
Err:23 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 lib32cilkrts5 amd64 7.4.0-1ubuntu1~18.04.1
  404  Not Found [IP: 52.168.50.79 80]
Err:24 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 libx32cilkrts5 amd64 7.4.0-1ubuntu1~18.04.1
  404  Not Found [IP: 52.168.50.79 80]
```

**Comment by sanan2015** [comment]
有大佬可以解答下吗

**Comment by a528596516** [comment]
删掉sudo apt-get update前的#

**Comment by sanan2015** [comment]
> 删掉sudo apt-get update前的#

感谢，该报错已解决

**Comment by sanan2015** [comment]
> 删掉sudo apt-get update前的#

再请教下，上传的时候报错：

```
Upload binaries to release0s
##[error]Input required and not supplied: repo_token
Run svenstaro/upload-release-action@v1-release
  with:
    file: /opt/images/*.trx
    tag: AtuoBuild
    overwrite: true
    file_glob: true
##[error]Input required and not supplied: repo_token
```

代码是这个
```
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.R_TOKEN }}
        file: /opt/images/*.trx
        tag: AtuoBuild
        overwrite: true
        file_glob: true
```

请问下应该怎么处理，感谢~
